# Generated by Django 4.2 on 2024-12-20 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
    ]
